// Automatisch aus „Weinhandel Masterdatei NEU.xlsx“, Tab „Bestand“, erzeugt.
// Berücksichtigt werden ausschließlich Weine mit Bestand aktuell > 0.
// Interne Einkaufspreise, Kundendaten und exakte Lagerzahlen werden nicht veröffentlicht.

export type Wine = {
  id: string;
  winery: string;
  region: string;
  name: string;
  vintage: number;
  availability: "Direkt verfügbar" | "Nur noch wenige Flaschen" | "Nur noch 1 Flasche";
  price: number;
  volume: number;
  unitPrice: number;
  category: string;
  grape: string;
  style: string;
  profile: string;
  featured: boolean;
};

export const inventoryAsOf = "1. September 2026";

export const wines: Wine[] = [
  {
    "id": "W0109",
    "winery": "Weingut Daniel Mattern",
    "region": "Rheinhessen",
    "name": "No Limit Sparkling alkoholfrei",
    "vintage": 2024,
    "availability": "Nur noch wenige Flaschen",
    "price": 13.9,
    "volume": 0.75,
    "unitPrice": 18.53,
    "category": "Alkoholfrei",
    "grape": "Cuvée",
    "style": "Alkoholfrei",
    "profile": "Alkoholfrei",
    "featured": false
  },
  {
    "id": "W0116",
    "winery": "Weingut Bischel",
    "region": "Rheinhessen",
    "name": "Riesling Sekt Brut",
    "vintage": 2022,
    "availability": "Direkt verfügbar",
    "price": 15.9,
    "volume": 0.75,
    "unitPrice": 21.2,
    "category": "Prickelnd",
    "grape": "Riesling",
    "style": "Brut",
    "profile": "Prickelnd",
    "featured": false
  },
  {
    "id": "W0103",
    "winery": "Weingut Daniel Mattern",
    "region": "Rheinhessen",
    "name": "Hop & Grape Perlwein / Secco",
    "vintage": 2024,
    "availability": "Direkt verfügbar",
    "price": 13.9,
    "volume": 0.75,
    "unitPrice": 18.53,
    "category": "Prickelnd",
    "grape": "Cuvée",
    "style": "Perlwein",
    "profile": "Prickelnd",
    "featured": false
  },
  {
    "id": "W0036",
    "winery": "Weingut Geisser",
    "region": "Pfalz",
    "name": "Chardonnay Sekt Brut",
    "vintage": 2020,
    "availability": "Direkt verfügbar",
    "price": 12.8,
    "volume": 0.75,
    "unitPrice": 17.07,
    "category": "Prickelnd",
    "grape": "Chardonnay",
    "style": "Brut",
    "profile": "Prickelnd",
    "featured": true
  },
  {
    "id": "W0068",
    "winery": "Schlossgut Diel",
    "region": "Nahe",
    "name": "Rosé de Diel",
    "vintage": 2022,
    "availability": "Direkt verfügbar",
    "price": 13.5,
    "volume": 0.75,
    "unitPrice": 18,
    "category": "Rosé",
    "grape": "Cuvée",
    "style": "Trocken",
    "profile": "Rosé",
    "featured": false
  },
  {
    "id": "W0112",
    "winery": "Weingut Bischel",
    "region": "Rheinhessen",
    "name": "Rosé Trocken",
    "vintage": 2023,
    "availability": "Direkt verfügbar",
    "price": 9.5,
    "volume": 0.75,
    "unitPrice": 12.67,
    "category": "Rosé",
    "grape": "Cuvée",
    "style": "Trocken",
    "profile": "Rosé",
    "featured": false
  },
  {
    "id": "W0097",
    "winery": "Weingut Daniel Mattern",
    "region": "Rheinhessen",
    "name": "Rosé",
    "vintage": 2024,
    "availability": "Nur noch 1 Flasche",
    "price": 9.5,
    "volume": 0.75,
    "unitPrice": 12.67,
    "category": "Rosé",
    "grape": "Cuvée",
    "style": "Trocken",
    "profile": "Rosé",
    "featured": false
  },
  {
    "id": "W0121",
    "winery": "Weingut Bischel",
    "region": "Rheinhessen",
    "name": "Appenheim Spätburgunder aus 1. Lagen",
    "vintage": 2019,
    "availability": "Direkt verfügbar",
    "price": 27,
    "volume": 0.75,
    "unitPrice": 36,
    "category": "Rotwein",
    "grape": "Spätburgunder",
    "style": "Trocken",
    "profile": "Rot & würzig",
    "featured": true
  },
  {
    "id": "W0113",
    "winery": "Weingut Bischel",
    "region": "Rheinhessen",
    "name": "Blaufränkisch VINTAGE",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 15.9,
    "volume": 0.75,
    "unitPrice": 21.2,
    "category": "Rotwein",
    "grape": "Blaufränkisch",
    "style": "Trocken",
    "profile": "Rot & würzig",
    "featured": false
  },
  {
    "id": "W0122",
    "winery": "Weingut Bischel",
    "region": "Rheinhessen",
    "name": "Gau-Algesheim Johannisberg Spätburgunder 1. Lage",
    "vintage": 2020,
    "availability": "Direkt verfügbar",
    "price": 30,
    "volume": 0.75,
    "unitPrice": 40,
    "category": "Rotwein",
    "grape": "Spätburgunder",
    "style": "Trocken",
    "profile": "Rot & würzig",
    "featured": false
  },
  {
    "id": "W0123",
    "winery": "Weingut Bischel",
    "region": "Rheinhessen",
    "name": "Pinot Noir Reserve",
    "vintage": 2020,
    "availability": "Nur noch wenige Flaschen",
    "price": 39,
    "volume": 0.75,
    "unitPrice": 52,
    "category": "Rotwein",
    "grape": "Spätburgunder",
    "style": "Trocken",
    "profile": "Rot & würzig",
    "featured": false
  },
  {
    "id": "W0084",
    "winery": "Weingut Christian Bamberger",
    "region": "Nahe",
    "name": "Spätburgunder Vulkangestein",
    "vintage": 2020,
    "availability": "Nur noch 1 Flasche",
    "price": 22,
    "volume": 0.75,
    "unitPrice": 29.33,
    "category": "Rotwein",
    "grape": "Spätburgunder",
    "style": "Trocken",
    "profile": "Rot & würzig",
    "featured": false
  },
  {
    "id": "W0085",
    "winery": "Weingut Christian Bamberger",
    "region": "Nahe",
    "name": "Spätburgunder Vulkangestein",
    "vintage": 2021,
    "availability": "Nur noch wenige Flaschen",
    "price": 22,
    "volume": 0.75,
    "unitPrice": 29.33,
    "category": "Rotwein",
    "grape": "Spätburgunder",
    "style": "Trocken",
    "profile": "Rot & würzig",
    "featured": false
  },
  {
    "id": "W0027",
    "winery": "Weingut Thanisch",
    "region": "Mosel",
    "name": "Spätburgunder Trocken unfiltriert Barrique",
    "vintage": 2020,
    "availability": "Direkt verfügbar",
    "price": 18.5,
    "volume": 0.75,
    "unitPrice": 24.67,
    "category": "Rotwein",
    "grape": "Spätburgunder",
    "style": "Trocken",
    "profile": "Rot & würzig",
    "featured": true
  },
  {
    "id": "W0028",
    "winery": "Weingut Thanisch",
    "region": "Mosel",
    "name": "Spätburgunder Trocken unfiltriert Barrique",
    "vintage": 2021,
    "availability": "Direkt verfügbar",
    "price": 19.5,
    "volume": 0.75,
    "unitPrice": 26,
    "category": "Rotwein",
    "grape": "Spätburgunder",
    "style": "Trocken",
    "profile": "Rot & würzig",
    "featured": false
  },
  {
    "id": "W0064",
    "winery": "Schlossgut Diel",
    "region": "Nahe",
    "name": "Nahesteiner Weißburgunder",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 12.9,
    "volume": 0.75,
    "unitPrice": 17.2,
    "category": "Weißwein",
    "grape": "Cuvée",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0066",
    "winery": "Schlossgut Diel",
    "region": "Nahe",
    "name": "Pinot Gris Reserve",
    "vintage": 2018,
    "availability": "Nur noch 1 Flasche",
    "price": 26,
    "volume": 0.75,
    "unitPrice": 34.67,
    "category": "Weißwein",
    "grape": "Grauburgunder",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0067",
    "winery": "Schlossgut Diel",
    "region": "Nahe",
    "name": "Prestige Cuvée Victor",
    "vintage": 2018,
    "availability": "Nur noch wenige Flaschen",
    "price": 45,
    "volume": 0.75,
    "unitPrice": 60,
    "category": "Weißwein",
    "grape": "Cuvée",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0114",
    "winery": "Weingut Bischel",
    "region": "Rheinhessen",
    "name": "Appenheimer Weißburgunder & Chardonnay",
    "vintage": 2023,
    "availability": "Nur noch wenige Flaschen",
    "price": 18.5,
    "volume": 0.75,
    "unitPrice": 24.67,
    "category": "Weißwein",
    "grape": "Chardonnay",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0115",
    "winery": "Weingut Bischel",
    "region": "Rheinhessen",
    "name": "Chardonnay Reserve",
    "vintage": 2022,
    "availability": "Direkt verfügbar",
    "price": 32,
    "volume": 0.75,
    "unitPrice": 42.67,
    "category": "Weißwein",
    "grape": "Chardonnay",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0111",
    "winery": "Weingut Bischel",
    "region": "Rheinhessen",
    "name": "Grauer Burgunder",
    "vintage": 2024,
    "availability": "Direkt verfügbar",
    "price": 10.9,
    "volume": 0.75,
    "unitPrice": 14.53,
    "category": "Weißwein",
    "grape": "Grauburgunder",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": true
  },
  {
    "id": "W0119",
    "winery": "Weingut Bischel",
    "region": "Rheinhessen",
    "name": "Riesling Heerkretz GG",
    "vintage": 2023,
    "availability": "Nur noch wenige Flaschen",
    "price": 45,
    "volume": 0.75,
    "unitPrice": 60,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken · GG",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0117",
    "winery": "Weingut Bischel",
    "region": "Rheinhessen",
    "name": "Riesling Hundertgulden GG",
    "vintage": 2023,
    "availability": "Nur noch wenige Flaschen",
    "price": 45,
    "volume": 0.75,
    "unitPrice": 60,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken · GG",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0118",
    "winery": "Weingut Bischel",
    "region": "Rheinhessen",
    "name": "Riesling Scharlachberg GG",
    "vintage": 2023,
    "availability": "Nur noch wenige Flaschen",
    "price": 49,
    "volume": 0.75,
    "unitPrice": 65.33,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken · GG",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0120",
    "winery": "Weingut Bischel",
    "region": "Rheinhessen",
    "name": "Riesling St. Laurenzikirche GG",
    "vintage": 2023,
    "availability": "Nur noch wenige Flaschen",
    "price": 45,
    "volume": 0.75,
    "unitPrice": 60,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken · GG",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0081",
    "winery": "Weingut Christian Bamberger",
    "region": "Nahe",
    "name": "Augenblick",
    "vintage": 2023,
    "availability": "Direkt verfügbar",
    "price": 9.5,
    "volume": 0.75,
    "unitPrice": 12.67,
    "category": "Weißwein",
    "grape": "Cuvée",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0080",
    "winery": "Weingut Christian Bamberger",
    "region": "Nahe",
    "name": "Glückslos",
    "vintage": 2023,
    "availability": "Nur noch wenige Flaschen",
    "price": 9.5,
    "volume": 0.75,
    "unitPrice": 12.67,
    "category": "Weißwein",
    "grape": "Cuvée",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0071",
    "winery": "Weingut Christian Bamberger",
    "region": "Nahe",
    "name": "Grauburgunder",
    "vintage": 2022,
    "availability": "Direkt verfügbar",
    "price": 8,
    "volume": 0.75,
    "unitPrice": 10.67,
    "category": "Weißwein",
    "grape": "Grauburgunder",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0082",
    "winery": "Weingut Christian Bamberger",
    "region": "Nahe",
    "name": "Riesling Vulkangestein Trocken",
    "vintage": 2021,
    "availability": "Nur noch 1 Flasche",
    "price": 15.5,
    "volume": 0.75,
    "unitPrice": 20.67,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0072",
    "winery": "Weingut Christian Bamberger",
    "region": "Nahe",
    "name": "Weissburgunder",
    "vintage": 2021,
    "availability": "Nur noch wenige Flaschen",
    "price": 9,
    "volume": 0.75,
    "unitPrice": 12,
    "category": "Weißwein",
    "grape": "Weißburgunder",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0100",
    "winery": "Weingut Daniel Mattern",
    "region": "Rheinhessen",
    "name": "Dittelsheimer Assemblage Réserve",
    "vintage": 2019,
    "availability": "Nur noch 1 Flasche",
    "price": 24.9,
    "volume": 0.75,
    "unitPrice": 33.2,
    "category": "Weißwein",
    "grape": "Cuvée",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0099",
    "winery": "Weingut Daniel Mattern",
    "region": "Rheinhessen",
    "name": "Dittelsheimer Chardonnay Reserve",
    "vintage": 2021,
    "availability": "Direkt verfügbar",
    "price": 13.9,
    "volume": 0.75,
    "unitPrice": 18.53,
    "category": "Weißwein",
    "grape": "Chardonnay",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0098",
    "winery": "Weingut Daniel Mattern",
    "region": "Rheinhessen",
    "name": "Grauburgunder",
    "vintage": 2023,
    "availability": "Nur noch wenige Flaschen",
    "price": 9.5,
    "volume": 0.75,
    "unitPrice": 12.67,
    "category": "Weißwein",
    "grape": "Grauburgunder",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0040",
    "winery": "Weingut Geisser",
    "region": "Pfalz",
    "name": "Sauvignon Blanc \"Sonnenberg\"",
    "vintage": 2022,
    "availability": "Direkt verfügbar",
    "price": 8.8,
    "volume": 0.75,
    "unitPrice": 11.73,
    "category": "Weißwein",
    "grape": "Sauvignon Blanc",
    "style": "Trocken",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0093",
    "winery": "Weingut Matthias Müller",
    "region": "Mittelrhein",
    "name": "Riesling Bopparder Hamm Kieselgallenschiefer",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 11.8,
    "volume": 0.75,
    "unitPrice": 15.73,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0094",
    "winery": "Weingut Matthias Müller",
    "region": "Mittelrhein",
    "name": "Riesling Feuerlay GG",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 30,
    "volume": 0.75,
    "unitPrice": 40,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken · GG",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0095",
    "winery": "Weingut Matthias Müller",
    "region": "Mittelrhein",
    "name": "Riesling Mandelstein GG",
    "vintage": 2021,
    "availability": "Nur noch 1 Flasche",
    "price": 34,
    "volume": 0.75,
    "unitPrice": 45.33,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken · GG",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0052",
    "winery": "Weingut Schloss Lieser",
    "region": "Mosel",
    "name": "Juffer Feinherb",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 19.5,
    "volume": 0.75,
    "unitPrice": 26,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Feinherb",
    "profile": "Feinherb & fruchtig",
    "featured": false
  },
  {
    "id": "W0054",
    "winery": "Weingut Schloss Lieser",
    "region": "Mosel",
    "name": "Juffer Kabinett Feinfruchtig",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 18,
    "volume": 0.75,
    "unitPrice": 24,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Feinherb",
    "profile": "Feinherb & fruchtig",
    "featured": false
  },
  {
    "id": "W0051",
    "winery": "Weingut Schloss Lieser",
    "region": "Mosel",
    "name": "Lieser Heldenstück Trocken",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 19.5,
    "volume": 0.75,
    "unitPrice": 26,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0053",
    "winery": "Weingut Schloss Lieser",
    "region": "Mosel",
    "name": "Niederberg Helden Feinherb",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 19.5,
    "volume": 0.75,
    "unitPrice": 26,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Feinherb",
    "profile": "Feinherb & fruchtig",
    "featured": false
  },
  {
    "id": "W0063",
    "winery": "Weingut Schloss Lieser",
    "region": "Mosel",
    "name": "Riesling GG Goldtröpfchen",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 38,
    "volume": 0.75,
    "unitPrice": 50.67,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken · GG",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0059",
    "winery": "Weingut Schloss Lieser",
    "region": "Mosel",
    "name": "Riesling GG Graacher Himmelreich",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 38,
    "volume": 0.75,
    "unitPrice": 50.67,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken · GG",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0061",
    "winery": "Weingut Schloss Lieser",
    "region": "Mosel",
    "name": "Riesling GG Juffer Sonnenuhr",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 38,
    "volume": 0.75,
    "unitPrice": 50.67,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken · GG",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0060",
    "winery": "Weingut Schloss Lieser",
    "region": "Mosel",
    "name": "Riesling GG Niederberg Helden",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 38,
    "volume": 0.75,
    "unitPrice": 50.67,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken · GG",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0062",
    "winery": "Weingut Schloss Lieser",
    "region": "Mosel",
    "name": "Riesling GG Wehlener Sonnenuhr",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 38,
    "volume": 0.75,
    "unitPrice": 50.67,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken · GG",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0057",
    "winery": "Weingut Schloss Lieser",
    "region": "Mosel",
    "name": "Riesling Goldtröpfchen Auslese",
    "vintage": 2022,
    "availability": "Direkt verfügbar",
    "price": 32,
    "volume": 0.75,
    "unitPrice": 42.67,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Fruchtsüß",
    "profile": "Feinherb & fruchtig",
    "featured": true
  },
  {
    "id": "W0056",
    "winery": "Weingut Schloss Lieser",
    "region": "Mosel",
    "name": "Riesling Niederberg Helden Auslese Goldkapsel",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 24,
    "volume": 0.375,
    "unitPrice": 64,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Fruchtsüß",
    "profile": "Feinherb & fruchtig",
    "featured": false
  },
  {
    "id": "W0048",
    "winery": "Weingut Schloss Lieser",
    "region": "Mosel",
    "name": "Weißburgunder Trocken",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 14.5,
    "volume": 0.75,
    "unitPrice": 19.33,
    "category": "Weißwein",
    "grape": "Weißburgunder",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0012",
    "winery": "Weingut Thanisch",
    "region": "Mosel",
    "name": "Alte Reben R Trocken",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 19.5,
    "volume": 0.75,
    "unitPrice": 26,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0002",
    "winery": "Weingut Thanisch",
    "region": "Mosel",
    "name": "Chardonnay",
    "vintage": 2023,
    "availability": "Nur noch 1 Flasche",
    "price": 9.9,
    "volume": 0.75,
    "unitPrice": 13.2,
    "category": "Weißwein",
    "grape": "Chardonnay",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0005",
    "winery": "Weingut Thanisch",
    "region": "Mosel",
    "name": "Chardonnay 500",
    "vintage": 2022,
    "availability": "Direkt verfügbar",
    "price": 19.5,
    "volume": 0.75,
    "unitPrice": 26,
    "category": "Weißwein",
    "grape": "Chardonnay",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0006",
    "winery": "Weingut Thanisch",
    "region": "Mosel",
    "name": "Chardonnay 500",
    "vintage": 2023,
    "availability": "Nur noch wenige Flaschen",
    "price": 19.5,
    "volume": 0.75,
    "unitPrice": 26,
    "category": "Weißwein",
    "grape": "Chardonnay",
    "style": "Trocken",
    "profile": "Rund & charaktervoll",
    "featured": false
  },
  {
    "id": "W0010",
    "winery": "Weingut Thanisch",
    "region": "Mosel",
    "name": "Riesling Spätlese Trocken Niederberg Helden",
    "vintage": 2022,
    "availability": "Nur noch 1 Flasche",
    "price": 13,
    "volume": 0.75,
    "unitPrice": 17.33,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken",
    "profile": "Frisch & mineralisch",
    "featured": false
  },
  {
    "id": "W0009",
    "winery": "Weingut Thanisch",
    "region": "Mosel",
    "name": "Tribut Grauschiefer Riesling",
    "vintage": 2023,
    "availability": "Direkt verfügbar",
    "price": 9.5,
    "volume": 0.75,
    "unitPrice": 12.67,
    "category": "Weißwein",
    "grape": "Riesling",
    "style": "Trocken",
    "profile": "Frisch & mineralisch",
    "featured": true
  },
  {
    "id": "W0090",
    "winery": "Weingut von Winning",
    "region": "Pfalz",
    "name": "Sauvignon Blanc II",
    "vintage": 2022,
    "availability": "Nur noch wenige Flaschen",
    "price": 11,
    "volume": 0.75,
    "unitPrice": 14.67,
    "category": "Weißwein",
    "grape": "Sauvignon Blanc",
    "style": "Trocken",
    "profile": "Frisch & mineralisch",
    "featured": false
  }
];
